import { useState } from "react";

const phone = "+91 86556 69966";
const address = "Shop No. 2, Bhukendra, Bus Stop, Pokharan Rd, near Yeoor Hills Road, Upvan, Thane West, Thane, Maharashtra 400606";
const classes = ["CrossFit", "Zumba", "Yoga", "Gym Floor"];

export default function App() {
  const [menu, setMenu] = useState(false);
  const [trial, setTrial] = useState(false);
  const [renew, setRenew] = useState(false);
  const [done, setDone] = useState(false);
  return <main>
    <header className="nav"><a className="brand" href="#top"><b>A</b><span>AVENGERS<small>FITNESS CLUB</small></span></a><button className="hamb" onClick={() => setMenu(!menu)}>☰</button><nav className={menu ? "open" : ""}>{[["Classes","classes"],["Membership","membership"],["Trainers","trainers"],["About","about"],["Contact","contact"]].map(([x,id]) => <a href={'#'+id} key={id} onClick={() => setMenu(false)}>{x}</a>)}<button onClick={() => setTrial(true)}>BOOK A TRIAL ↗</button></nav></header>
    <section id="top" className="hero"><div><label>UPVAN · THANE WEST</label><h1>TRAIN HARD.<br/><i>LIVE STRONG.</i></h1><p>A focused fitness space for strength, conditioning, movement and consistency. Find your training rhythm at Avengers Fitness Club.</p><button className="primary" onClick={() => setTrial(true)}>BOOK A TRIAL ↗</button><div className="proof"><b>4.7 ★</b><span>from 1,325 reviews</span><b>4</b><span>training formats</span></div></div><div className="hero-art"><strong>FIT</strong><small>BUILD YOUR<br/>BASE.</small></div></section>
    <section id="classes" className="dark"><label>01 / TRAINING</label><h2>FIND YOUR <i>MODE.</i></h2><div className="grid">{classes.map((x,i)=><article key={x}><small>0{i+1}</small><strong>{x}</strong><p>{x === "CrossFit" ? "Strength, conditioning & functional movement" : x === "Zumba" ? "Dance-led fitness with high-energy movement" : x === "Yoga" ? "Mobility, balance & mindful movement" : "Independent training with a full fitness focus"}</p></article>)}</div><aside>Class schedules are being prepared for online publishing. Contact the club for the current timetable.</aside></section>
    <section id="membership" className="light"><label>02 / MEMBERSHIP</label><h2>YOUR ROUTINE.<br/><i>YOUR COMMITMENT.</i></h2><p>Membership plans and pricing will appear here once the club's live plan data is connected. No made-up prices.</p><button className="primary" onClick={() => setRenew(true)}>RENEW MEMBERSHIP</button></section>
    <section id="trainers" className="dark"><label>03 / COACHING</label><h2>TRAIN WITH <i>INTENT.</i></h2><div className="empty"><b>+</b><h3>Trainer booking is ready to connect.</h3><p>No trainer profiles or availability have been supplied yet, so this page does not invent them.</p><button onClick={() => setTrial(true)}>ASK ABOUT COACHING ↗</button></div></section>
    <section id="about" className="about"><div className="giant">A</div><div><label>04 / THE CLUB</label><h2>BUILT FOR<br/><i>CONSISTENCY.</i></h2><p>Avengers Fitness Club is a fitness center and CrossFit-focused training space in Upvan, Thane West, offering gym training alongside Zumba and yoga.</p><p>The website is designed around a simple path: discover → explore → book a trial → join → renew.</p><small>{address}</small></div></section>
    <section id="contact" className="contact"><div><label>05 / CONTACT</label><h2>READY WHEN<br/><i>YOU ARE.</i></h2><p>Questions about classes, membership or current availability? Contact the club directly.</p><a className="primary darkbtn" href="tel:+918655669966">CALL {phone} ↗</a></div><div className="card"><b>UPVAN · THANE WEST</b><p>{address}</p><a href="https://www.google.com/maps/search/?api=1&query=Avengers+Fitness+Club+Upvan+Thane">OPEN IN MAPS ↗</a></div></section>
    <footer>AVENGERS FITNESS CLUB <span>UPVAN · THANE WEST</span><span>© 2026</span></footer>
    {trial && <div className="modal"><div><button className="x" onClick={() => {setTrial(false);setDone(false)}}>×</button>{!done ? <><label>TRIAL REQUEST</label><h2>START YOUR <i>FIRST SESSION.</i></h2><form onSubmit={e => {e.preventDefault();setDone(true)}}><input required placeholder="Name"/><input required placeholder="Phone" type="tel"/><select required defaultValue=""><option value="" disabled>Select a format</option>{classes.map(x=><option key={x}>{x}</option>)}</select><button className="primary">SEND TRIAL REQUEST ↗</button></form></> : <><h2>REQUEST <i>READY.</i></h2><p>Your details were validated locally. No booking was claimed.</p><a className="primary" href="tel:+918655669966">CALL {phone} ↗</a></>}</div></div>}
    {renew && <div className="modal"><div><button className="x" onClick={() => setRenew(false)}>×</button><label>MEMBERSHIP RENEWAL</label><h2>KEEP THE <i>STREAK ALIVE.</i></h2><p>Enter member details. Payment and membership APIs can be connected without changing this interface.</p><form onSubmit={e => {e.preventDefault();setRenew(false)}}><input required placeholder="Member name"/><input required placeholder="Registered phone"/><input required placeholder="Membership ID"/><button className="primary">CONTINUE TO RENEWAL ↗</button></form></div></div>}
  </main>;
}
